# -*- coding: utf-8 -*-
"""Day 04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rfcYCvVXfv0Rz5A-t1GNdJpTewijf2ZS

## Power Rule & Subplots Practice

Given function:  
**f(x) = 3x³ + 2x² − 5x + 7**
"""

import numpy as np
import matplotlib.pyplot as plt

def f(X):
  return 3*X**3+2*X**2-5*X+7

def df(x):
    return 9 * x**2 + 4 * x - 5

x_1 = np.linspace(-10, 10, 400)

plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.title('function')
plt.xlabel('X', fontsize=16)
plt.ylabel('f(x)', fontsize=16)
plt.plot(x_1, f(x_1))

plt.subplot(1, 2, 2)
plt.title('derivative')
plt.xlabel('X', fontsize=16)
plt.ylabel("f'(x)", fontsize=16)
plt.plot(x_1, df(x_1))
plt.show()